[package]
name = "tgreddit"
version = "0.1.0"
edition = "2024"
description = "Get the top posts of your favorite subreddits to Telegram"
license = "MIT"

[dependencies]
anyhow = "1.0.102"
chrono = "0.4.44"
duct = "1.1.1"
env_logger = "0.11.9"
getopts = "0.2.24"
itertools = "0.15.0"
lazy_static = "1.5.0"
log = "0.4.29"
regex = { version = "1.12.3", default-features = false, features = [
    "std",
    "unicode-perl",
] }
rusqlite = { version = "0.40.2", features = ["chrono", "bundled"] }
rusqlite_migration = "2.6.0"
secrecy = { version = "0.10.3", features = ["serde"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_derive = "1.0.144"
serde_json = "1.0.149"
signal-hook = "0.4.4"
strum = "0.28.0"
strum_macros = "0.28.0"
teloxide = { version = "0.17.0", features = ["macros"] }
tempfile = "3.26.0"
thiserror = "2.0.18"
tokio = { version = "1.50.0", features = ["rt-multi-thread", "macros", "sync"] }
toml = "1.1.4"
url = "2.5.8"
xdg = "3.0.0"
reqwest = { version = "0.13.4", features = ["json", "query"] }

# Use vendored openssl. We don't depend on it directly.
openssl = { version = "0.10.75", features = ["vendored"], optional = true }

[features]
vendored-openssl = ["openssl"]
